--[[
SetGlobalString("blank_1", "                       ")
SetGlobalString("blank_2", "                       ")
SetGlobalString("blank_3", "                       ")
SetGlobalString("blank_4", "                       ")
SetGlobalString("blank_5", "                       ")
SetGlobalString("blank_6", "                       ")
SetGlobalString("blank_7", "                       ")
SetGlobalString("blank_8", "   (Strengths):         ")
SetGlobalString("blank_9", "                        ")
SetGlobalString("blank_10", "(Weaknesses):          ")
SetGlobalString("blank_11", "                       ")
SetGlobalString("blank_12", "  (Strats):            ")
SetGlobalString("blank_13", "                       ")
]]--
-- Rollermine
SetGlobalString("rollermine_1", "These things roll")
SetGlobalString("rollermine_2", "They can be pretty threatening with")
SetGlobalString("rollermine_3", "sufficient numbers, but on their")
SetGlobalString("rollermine_4", "own aren't great. Probably one")
SetGlobalString("rollermine_5", "of the better lower-tier units")
SetGlobalString("rollermine_6", "                           ")
SetGlobalString("rollermine_8", "    (Strengths): killing other melee units")
SetGlobalString("rollermine_9", "                         ")
SetGlobalString("rollermine_10", "(Weaknesses): Explosions")
SetGlobalString("rollermine_11", "                        ")
SetGlobalString("rollermine_12", "   (Strats): Get a shit ton of them")
SetGlobalString("rollermine_13", "                        ")
-- Double Rollermine
SetGlobalString("doublerollermine_1", "Double the balls, double the power.")
SetGlobalString("doublerollermine_2", "Very good for second tier units")
SetGlobalString("doublerollermine_3", "Not sure if you've noticed,")
SetGlobalString("doublerollermine_4", "but they explode on death")
SetGlobalString("doublerollermine_5", "                           ")
SetGlobalString("doublerollermine_6", "                           ")
SetGlobalString("doublerollermine_8", "    (Strengths): Killing other melee units")
SetGlobalString("doublerollermine_9", "                         ")
SetGlobalString("doublerollermine_10", "(Weaknesses): Explosions, Ranged")
SetGlobalString("doublerollermine_11", "                        ")
SetGlobalString("doublerollermine_12", "   (Strats): Get even more of them")
SetGlobalString("doublerollermine_13", "        (x3 and x4 exist btw)")
-- Triple Rollermine
SetGlobalString("triplerollermine_1", "Triple the balls, triple the power.")
SetGlobalString("triplerollermine_2", "Getting close to critical mass.")
SetGlobalString("triplerollermine_3", "These things make a nice horde")
SetGlobalString("triplerollermine_4", "                             ")
SetGlobalString("triplerollermine_5", "                             ")
SetGlobalString("triplerollermine_6", "                             ")
SetGlobalString("triplerollermine_8", "    (Strengths): Killing other melee units")
SetGlobalString("triplerollermine_9", "                         ")
SetGlobalString("triplerollermine_10", "(Weaknesses): Explosions, Ranged")
SetGlobalString("triplerollermine_11", "                        ")
SetGlobalString("triplerollermine_12", "   (Strats): More balls")
SetGlobalString("triplerollermine_13", "                        ")
-- Quin Rollermine
SetGlobalString("quinrollermine_1", "Maximum balls achieved.")
SetGlobalString("quinrollermine_2", "Your opponents weep.")
SetGlobalString("quinrollermine_3", "                             ")
SetGlobalString("quinrollermine_4", "                             ")
SetGlobalString("quinrollermine_5", "                             ")
SetGlobalString("quinrollermine_6", "                             ")
SetGlobalString("quinrollermine_8", "    (Strengths): Ball")
SetGlobalString("quinrollermine_9", "                         ")
SetGlobalString("quinrollermine_10", "(Weaknesses): not having enough")
SetGlobalString("quinrollermine_11", "                        ")
SetGlobalString("quinrollermine_12", "   (Strats): More balls")
SetGlobalString("quinrollermine_13", "                        ")
-- Combine Sniper
SetGlobalString("sniper_1", "Very powerful long range unit.")
SetGlobalString("sniper_2", "Dont have very much hp.")
SetGlobalString("sniper_3", "They're very accurate and can")
SetGlobalString("sniper_4", "easily shoot flying enemies")
SetGlobalString("sniper_5", "out of the air.")
SetGlobalString("sniper_6", "                        ")
SetGlobalString("sniper_7", "                        ")
SetGlobalString("sniper_8", "   (Strengths): Range")
SetGlobalString("sniper_9", "                        ")
SetGlobalString("sniper_10", "(Weaknesses): Explosions")
SetGlobalString("sniper_11", "                        ")
SetGlobalString("sniper_12", "  (Strats): Probably better in the")
SetGlobalString("sniper_13", "             backline.")
-- Double sniper
SetGlobalString("doublesniper_1", "Very powerful long range unit.")
SetGlobalString("doublesniper_2", "Dont have very much hp.")
SetGlobalString("doublesniper_3", "They're very accurate and can")
SetGlobalString("doublesniper_4", "easily shoot flying enemies")
SetGlobalString("doublesniper_5", "out of the air.")
SetGlobalString("doublesniper_6", "Double the snipers, double the power.")
SetGlobalString("doublesniper_7", "                        ")
SetGlobalString("doublesniper_8", "   (Strengths): Range")
SetGlobalString("doublesniper_9", "                        ")
SetGlobalString("doublesniper_10", "(Weaknesses): Explosions")
SetGlobalString("doublesniper_11", "                        ")
SetGlobalString("doublesniper_12", "  (Strats): Probably better in the")
SetGlobalString("doublesniper_13", "             backline.")
-- Stalker
SetGlobalString("stalker_1", "High damage laser unit")
SetGlobalString("stalker_2", "with pretty decent HP.")
SetGlobalString("stalker_3", "Doesn't move very much though,")
SetGlobalString("stalker_4", "and they WILL friendly fire")
SetGlobalString("stalker_5", "all your units by accident")
SetGlobalString("stalker_6", "if given the chance.")
SetGlobalString("stalker_7", "                        ")
SetGlobalString("stalker_8", "   (Strengths): Extreme range")
SetGlobalString("stalker_9", "                        ")
SetGlobalString("stalker_10", "(Weaknesses): Slow/immobile")
SetGlobalString("stalker_11", "                        ")
SetGlobalString("stalker_12", "  (Strats): May be better paired with units")
SetGlobalString("stalker_13", "            not at their height to avoid FF")
-- Double Stalker
SetGlobalString("doublestalker_1", "Double the lasers, double")
SetGlobalString("doublestalker_2", "the damage, and also double")
SetGlobalString("doublestalker_3", "the chances of friendly fire.")
SetGlobalString("doublestalker_4", "                        ")
SetGlobalString("doublestalker_5", "                        ")
SetGlobalString("doublestalker_6", "                        ")
SetGlobalString("doublestalker_7", "                        ")
SetGlobalString("doublestalker_8", "   (Strengths): Extreme range")
SetGlobalString("doublestalker_9", "                        ")
SetGlobalString("doublestalker_10", "(Weaknesses): Slow/immobile")
SetGlobalString("doublestalker_11", "                        ")
SetGlobalString("doublestalker_12", "  (Strats): Avoid putting behind")
SetGlobalString("doublestalker_13", "             friendly units")
-- Grenadier
SetGlobalString("grenadier_1", "Dedicated grenade thrower.")
SetGlobalString("grenadier_2", "Throws grenades very frequently,")
SetGlobalString("grenadier_3", "(should be) unable to actually shoot")
SetGlobalString("grenadier_4", "Use with caution, they can easily")
SetGlobalString("grenadier_5", "wipe your own team out with one or")
SetGlobalString("grenadier_6", "two badly placed grenades.")
SetGlobalString("grenadier_7", "                        ")
SetGlobalString("grenadier_8", "   (Strengths): Horde clear")
SetGlobalString("grenadier_9", "                        ")
SetGlobalString("grenadier_10", "(Weaknesses): Close / Long range")
SetGlobalString("grenadier_11", "                       ")
SetGlobalString("grenadier_12", "  (Strats): Perhaps send them first")
SetGlobalString("grenadier_13", "          to avoid FF")
-- Double Grenadier
SetGlobalString("doublegrenadier_1", "Whole lot more grenades comin.")
SetGlobalString("doublegrenadier_2", "These things will wipe the map.")
SetGlobalString("doublegrenadier_3", "(should be) unable to actually shoot.")
SetGlobalString("doublegrenadier_4", "Use with great caution.")
SetGlobalString("doublegrenadier_5", "                        ")
SetGlobalString("doublegrenadier_6", "                        ")
SetGlobalString("doublegrenadier_7", "                        ")
SetGlobalString("doublegrenadier_8", "   (Strengths): Many. Many nades.")
SetGlobalString("doublegrenadier_9", "                        ")
SetGlobalString("doublegrenadier_10", "(Weaknesses): Will squad wipe own team")
SetGlobalString("doublegrenadier_11", "                       ")
SetGlobalString("doublegrenadier_12", "  (Strats): Channel the spirit of Lebron")
SetGlobalString("doublegrenadier_13", "                       ")
-- Aegis Shield Unit
SetGlobalString("aegisshieldunit_1", "Extremely advanced soldiers sent")
SetGlobalString("aegisshieldunit_2", "from the future to help you win.")
SetGlobalString("aegisshieldunit_3", "Armed with a disposable energy")
SetGlobalString("aegisshieldunit_4", "shield which blocks enemy bullets")
SetGlobalString("aegisshieldunit_5", "Otherwise identical to Combine SMGs")
SetGlobalString("aegisshieldunit_6", "                       ")
SetGlobalString("aegisshieldunit_7", "                       ")
SetGlobalString("aegisshieldunit_8", "   (Strengths): Versing ranged units")
SetGlobalString("aegisshieldunit_9", "                        ")
SetGlobalString("aegisshieldunit_10", "(Weaknesses): Melee, explosion units")
SetGlobalString("aegisshieldunit_11", "                       ")
SetGlobalString("aegisshieldunit_12", "  (Strats): Can shield units weak to")
SetGlobalString("aegisshieldunit_13", "             ranged/bullets")
-- Hunter Unit
SetGlobalString("hunter_1", "Mechanical tripods equipped with")
SetGlobalString("hunter_2", "anti-matter flechette cannon.")
SetGlobalString("hunter_3", "Highly aggressive.")
SetGlobalString("hunter_4", "Will charge and melee enemies")
SetGlobalString("hunter_5", "dealing lots of damage.")
SetGlobalString("hunter_6", "                       ")
SetGlobalString("hunter_7", "                       ")
SetGlobalString("hunter_8", "   (Strengths): Strong melee unit")
SetGlobalString("hunter_9", "                        ")
SetGlobalString("hunter_10", "(Weaknesses): High single target")
SetGlobalString("hunter_11", "          damage / explosions")
SetGlobalString("hunter_12", "  (Strats): Good as frontliners") 
SetGlobalString("hunter_13", "                       ")
-- Double Hunter Unit
SetGlobalString("doublehunter_1", "Mechanical tripods equipped with")
SetGlobalString("doublehunter_2", "anti-matter flechette cannon.")
SetGlobalString("doublehunter_3", "Highly aggressive.")
SetGlobalString("doublehunter_4", "Will charge and melee enemies")
SetGlobalString("doublehunter_5", "dealing lots of damage.")
SetGlobalString("doublehunter_6", "Now with double the hunters!")
SetGlobalString("doublehunter_7", "                        ")
SetGlobalString("doublehunter_8", "   (Strengths): Strong melee unit")
SetGlobalString("doublehunter_9", "                        ")
SetGlobalString("doublehunter_10", "(Weaknesses): High single target")
SetGlobalString("doublehunter_11", "          damage / explosions")
SetGlobalString("doublehunter_12", "  (Strats): Good as frontliners") 
SetGlobalString("doublehunter_13", "                       ")
-- Acid Spitter Unit
SetGlobalString("acidspitter_1", "Antlion workers adapted for")
SetGlobalString("acidspitter_2", "ranged attacks. Kinda squishy,")
SetGlobalString("acidspitter_3", "deals great damage from across")
SetGlobalString("acidspitter_4", "the map. Acid explodes on impact,")
SetGlobalString("acidspitter_5", "doing poison damage in an area.")
SetGlobalString("acidspitter_6", "                       ")
SetGlobalString("acidspitter_7", "                       ")
SetGlobalString("acidspitter_8", "   (Strengths): Long ranged artillery")
SetGlobalString("acidspitter_9", "                        ")
SetGlobalString("acidspitter_10", "(Weaknesses): Pretty fragile")
SetGlobalString("acidspitter_11", "                       ")
SetGlobalString("acidspitter_12", "  (Strats): Put in backline")
SetGlobalString("acidspitter_13", "                       ")
-- Double Acid Spitter Unit
SetGlobalString("doubleacidspitter_1", "Antlion workers adapted for")
SetGlobalString("doubleacidspitter_2", "ranged attacks. Kinda squishy,")
SetGlobalString("doubleacidspitter_3", "deals great damage from across")
SetGlobalString("doubleacidspitter_4", "the map. Acid explodes on impact,")
SetGlobalString("doubleacidspitter_5", "doing poison damage in an area.")
SetGlobalString("doubleacidspitter_6", "The horde grows...     ")
SetGlobalString("doubleacidspitter_7", "                       ")
SetGlobalString("doubleacidspitter_8", "   (Strengths): Long ranged artillery")
SetGlobalString("doubleacidspitter_9", "                        ")
SetGlobalString("doubleacidspitter_10", "(Weaknesses): Pretty fragile")
SetGlobalString("doubleacidspitter_11", "                       ")
SetGlobalString("doubleacidspitter_12", "  (Strats): Put in backline")
SetGlobalString("doubleacidspitter_13", "                       ")
-- Quad Acid Spitter Unit
SetGlobalString("quadacidspitter_1", "Your enemies have pissed off")
SetGlobalString("quadacidspitter_2", "a rather large colony it seems.")
SetGlobalString("quadacidspitter_3", "Sucks for them! prepare for")
SetGlobalString("quadacidspitter_4", " mad hunk speeg...     ")
SetGlobalString("quadacidspitter_5", "                       ")
SetGlobalString("quadacidspitter_6", "                       ")
SetGlobalString("quadacidspitter_7", "                       ")
SetGlobalString("quadacidspitter_8", "   (Strengths): The Horde.")
SetGlobalString("quadacidspitter_9", "                        ")
SetGlobalString("quadacidspitter_10", "(Weaknesses): AOE attacks")
SetGlobalString("quadacidspitter_11", "                       ")
SetGlobalString("quadacidspitter_12", "  (Strats): Get strength 4")
SetGlobalString("quadacidspitter_13", "                       ")
-- Headcrab
SetGlobalString("headcrab_1", "Headcrabs are the default mob, mostly")
SetGlobalString("headcrab_2", "because they're the worst. Headcrabs")
SetGlobalString("headcrab_3", "are slow, weak, and inarguably the")
SetGlobalString("headcrab_4", "least tasty subspecies of crab.")
SetGlobalString("headcrab_5", "It is recommended you randomize them")
SetGlobalString("headcrab_6", "as soon as possible")
SetGlobalString("headcrab_8", "    (Strengths): None")
SetGlobalString("headcrab_9", "                         ")
SetGlobalString("headcrab_10", "(Weaknesses): Everything")
SetGlobalString("headcrab_11", "                        ")
SetGlobalString("headcrab_12", "   (Strats): Get a new Mob")
SetGlobalString("headcrab_13", "                   ")
-- Black Headcrab
SetGlobalString("blackheadcrab_1", "Black Headcrabs poision their")
SetGlobalString("blackheadcrab_2", "enemies, bringing most mobs down")
SetGlobalString("blackheadcrab_3", "to 1 health in a single hit. ")
SetGlobalString("blackheadcrab_4", "However, they are painfully slow,")
SetGlobalString("blackheadcrab_5", "and unable to actually finish other")
SetGlobalString("blackheadcrab_6", "mobs off. ")
SetGlobalString("blackheadcrab_8", "    (Strengths): 1 Hit Potential,")
SetGlobalString("blackheadcrab_9", "                        Jumpy Boi")
SetGlobalString("blackheadcrab_10", "(Weaknesses): Its really fricken slow")
SetGlobalString("blackheadcrab_11", "                        ")
SetGlobalString("blackheadcrab_12", "   (Strats): Send it out first and ")
SetGlobalString("blackheadcrab_13", "                  hope it makes it in time")
-- Fast Headcrab
SetGlobalString("fastheadcrab_1", "Fast headcrabs are the most battle")
SetGlobalString("fastheadcrab_2", "effective headcrab by far. Super ")
SetGlobalString("fastheadcrab_3", "strong in great numbers, same health ")
SetGlobalString("fastheadcrab_4", "as a regular headcrab but 5 times as")
SetGlobalString("fastheadcrab_5", "fast, these are dangerous opponents ")
SetGlobalString("fastheadcrab_6", "in high enough numbers")
SetGlobalString("fastheadcrab_8", "    (Strengths): Speed, Hard to hit")
SetGlobalString("fastheadcrab_9", "                        ")
SetGlobalString("fastheadcrab_10", "(Weaknesses): Explosions")
SetGlobalString("fastheadcrab_11", "                        ")
SetGlobalString("fastheadcrab_12", "   (Strats): Get as many as you can")
SetGlobalString("fastheadcrab_13", "                  and unleash the flood")
-- Manhack
SetGlobalString("manhack_1", "Manhacks are a great nuisance, as ")
SetGlobalString("manhack_2", "they don't do too much damage but")
SetGlobalString("manhack_3", "they piss ranged units off, ")
SetGlobalString("manhack_4", "ESPECIALLY ROCKETEERS! They confuse")
SetGlobalString("manhack_5", "the crap out of the ai when there")
SetGlobalString("manhack_6", "are more than 3 attacking one mob.")
SetGlobalString("manhack_8", "    (Strengths): Speed, Maneuverability,")
SetGlobalString("manhack_9", "                         hard to hit")
SetGlobalString("manhack_10", "(Weaknesses): Rather Squishy, Monks")
SetGlobalString("manhack_11", "                         ")
SetGlobalString("manhack_12", "   (Strats): Mob melee units,")
SetGlobalString("manhack_13", "                  confuse ranged units")
-- Crowbar Guy
SetGlobalString("crowbar_1", "Just a guy that got lost on his way home")
SetGlobalString("crowbar_2", "from work, so I took him and cloned him.")
SetGlobalString("crowbar_3", "His AI is pretty dumb sometimes, but for")
SetGlobalString("crowbar_4", "a common mob, he has average health,")
SetGlobalString("crowbar_5", "speed, and damage. His Boss says he's")
SetGlobalString("crowbar_6", "average in every way, and he's right.")
SetGlobalString("crowbar_8", "    (Strengths): Good Looking")
SetGlobalString("crowbar_9", "                         ")
SetGlobalString("crowbar_10", "(Weaknesses): Amidst a Divorce")
SetGlobalString("crowbar_11", "                         ")
SetGlobalString("crowbar_12", "   (Strats): Use as cannon fodder")
SetGlobalString("crowbar_13", "                   ")
-- Fast Torso
SetGlobalString("fasttorso_1", "Bigg Butt Jim's cousin, ChickenLegg")
SetGlobalString("fasttorso_2", "Joe. ChickenLegg Joe decided as a child")
SetGlobalString("fasttorso_3", "to only move around with his arms. Joe")
SetGlobalString("fasttorso_4", "swung around like a monkey in 'Nam")
SetGlobalString("fasttorso_5", "before a face full of friendly Napalm")
SetGlobalString("fasttorso_6", "burned him beyond recognition.")
SetGlobalString("fasttorso_8", "    (Strengths): Really fast, Tankiness, ")
SetGlobalString("fasttorso_9", "                         can do 50 pullups")
SetGlobalString("fasttorso_10", "(Weaknesses): Very few, except flying ")
SetGlobalString("fasttorso_11", "                        units or Monks")
SetGlobalString("fasttorso_12", "   (Strats): Release first to make")
SetGlobalString("fasttorso_13", "                  enemy ranged units miss")
-- Stop Resisting
SetGlobalString("stun_1", "An ex-cop with anger issues and a")
SetGlobalString("stun_2", "stun stick. Very aggressive, very ")
SetGlobalString("stun_3", "effective in numbers, very strong,")
SetGlobalString("stun_4", "hates horse raddish, can't drive stick,")
SetGlobalString("stun_5", "and after failing to get his counseling")
SetGlobalString("stun_6", "degree, beat the professor to death")
SetGlobalString("stun_8", "    (Strengths): Health, Speed, Lack of")
SetGlobalString("stun_9", "                         Compassion, Batting")
SetGlobalString("stun_10", "(Weaknesses): Very few, except")
SetGlobalString("stun_11", "                        Rocketeers")
SetGlobalString("stun_12", "   (Strats): Release first and watch them")
SetGlobalString("stun_13", "                  peacefully disperse a crowd")
-- Zombie Torso
SetGlobalString("torso_1", "Back in 'Nam, this guy's name was Bigg")
SetGlobalString("torso_2", "Butt Jim. (Yes, Bigg with 2 g's.) However,")
SetGlobalString("torso_3", "an IED he found in the jungle made from  ")
SetGlobalString("torso_4", "rusty nails and a Sprite can ruined his ")
SetGlobalString("torso_5", "chances of ever having a child with ")
SetGlobalString("torso_6", "his wife, so she left him back in 71.")
SetGlobalString("torso_8", "    (Strengths): Upper Body, lots")
SetGlobalString("torso_9", "                        of Health")
SetGlobalString("torso_10", "(Weaknesses): PTSD, a fear of the ")
SetGlobalString("torso_11", "                        color Green")
SetGlobalString("torso_12", "   (Strats): Use as cannon fodder. It ")
SetGlobalString("torso_13", "                  reminds him of 'Nam")
-- Medic
SetGlobalString("medic_1", "After graduating from Harvard Med, this")
SetGlobalString("medic_2", "kind soul enlisted to serve overseas as")
SetGlobalString("medic_3", "a combat medic. However, the horrors ")
SetGlobalString("medic_4", "she saw in the Pacific Theatre scarred")
SetGlobalString("medic_5", "her, which explains why sometimes her")
SetGlobalString("medic_6", "AI ignores the mob right next to her")
SetGlobalString("medic_8", "    (Strengths): Heals ally, can attack")
SetGlobalString("medic_9", "                         enemies albiet slowly")
SetGlobalString("medic_10", "(Weaknesses): Ranged units, the horrors")
SetGlobalString("medic_11", "                        of war made her hollow")
SetGlobalString("medic_12", "   (Strats): Release them right after the")
SetGlobalString("medic_13", "                  mob you want her to heal")
-- Shotgun
SetGlobalString("shotgun_1", "Shotguns are the standard combine")
SetGlobalString("shotgun_2", "soldier armed with an Italian SPAZ-12.")
SetGlobalString("shotgun_3", "Very high damage output, moderate")
SetGlobalString("shotgun_4", "speed, and squadwork capabilities")
SetGlobalString("shotgun_5", "heavily outweigh its occasional")
SetGlobalString("shotgun_6", "numskulled AI")
SetGlobalString("shotgun_8", "    (Strengths): High DPS, can nail a clay")
SetGlobalString("shotgun_9", "                         pigeon at 100 yards")
SetGlobalString("shotgun_10", "(Weaknesses): Will occasionally default")
SetGlobalString("shotgun_11", "                        to melee charges")
SetGlobalString("shotgun_12", "   (Strats): Release after other melee units")
SetGlobalString("shotgun_13", "                  to make full use of his gun")
-- SMG
SetGlobalString("combinesmg_1", "SMGS are the standard Combine Soldier")
SetGlobalString("combinesmg_2", "armed with a German MP7. The perfect")
SetGlobalString("combinesmg_3", "balance of range, damage, health, speed,")
SetGlobalString("combinesmg_4", "and reliability. Works really well with")
SetGlobalString("combinesmg_5", "other Combine Units, and provides great")
SetGlobalString("combinesmg_6", "backup for faster Melee units.")
SetGlobalString("combinesmg_8", "    (Strengths): Good DPS, Good Health")
SetGlobalString("combinesmg_9", "                         Good Aim, Reliable")
SetGlobalString("combinesmg_10", "(Weaknesses): None in particular")
SetGlobalString("combinesmg_11", "                        ")
SetGlobalString("combinesmg_12", "   (Strats): The Ideal soldier. Use for ")
SetGlobalString("combinesmg_13", "                  whatever purpose you wish")
-- Metrocop
SetGlobalString("cop_1", "These Metro Police are a good step up")
SetGlobalString("cop_2", "from Common mobs, as they are armed")
SetGlobalString("cop_3", "with a 9mm Pistol, and a Manhack that")
SetGlobalString("cop_4", "they can deploy. Overall smart AI, added")
SetGlobalString("cop_5", "bonus of a manhack, and decent accuracy")
SetGlobalString("cop_6", "make this a decent mob.")
SetGlobalString("cop_8", "    (Strengths): Range, Manhack")
SetGlobalString("cop_9", "                         ")
SetGlobalString("cop_10", "(Weaknesses): Zombies or other fast ")
SetGlobalString("cop_11", "                        melee mobs")
SetGlobalString("cop_12", "   (Strats): Release after some melees to")
SetGlobalString("cop_13", "                  keep it out of direct danger")
-- Stop Resisting (x2)
SetGlobalString("doublestun_1", "After breaking into a school and beating")
SetGlobalString("doublestun_2", "eight 1st graders to death in \"self ")
SetGlobalString("doublestun_3", "defense,\" the Minneapolis Police Depart.")
SetGlobalString("doublestun_4", "transfered these officers to Black Mesa,")
SetGlobalString("doublestun_5", "where their overagresive habbits and their")
SetGlobalString("doublestun_6", "baseball abilities could be better studied")
SetGlobalString("doublestun_8", "    (Strengths): Health, Speed, Lack of")
SetGlobalString("doublestun_9", "                         Compassion, Batting")
SetGlobalString("doublestun_10", "(Weaknesses): Very few, except")
SetGlobalString("doublestun_11", "                        Rocketeers")
SetGlobalString("doublestun_12", "   (Strats): Release first and watch them")
SetGlobalString("doublestun_13", "                  peacefully disperse a crowd")
-- Zombie
SetGlobalString("zombie_1", "Zombies are actually the Fast Zombie")
SetGlobalString("zombie_2", "HL2 because Regular Zombies were way")
SetGlobalString("zombie_3", "too slow. Zombies are fast, fairly")
SetGlobalString("zombie_4", "light mobs that deal good melee damage,")
SetGlobalString("zombie_5", "have a pretty good amount of health, and,")
SetGlobalString("zombie_6", "like Antlioins, are great in groups")
SetGlobalString("zombie_8", "    (Strengths): Fast, deal good damage,")
SetGlobalString("zombie_9", "                         Got massive hops")
SetGlobalString("zombie_10", "(Weaknesses): Explosions, Monks,")
SetGlobalString("zombie_11", "                        has a 680 SAT Score")
SetGlobalString("zombie_12", "   (Strats): Due to their speed, release")
SetGlobalString("zombie_13", "                  them after other melee units")
-- Antlion
SetGlobalString("antlion_1", "Fast, agile, jumpy, Antlions are a solid")
SetGlobalString("antlion_2", "offensive mob. Many of them served")
SetGlobalString("antlion_3", "storming Nova Prospekt, making use of")
SetGlobalString("antlion_4", "their wings and their numbers to over-")
SetGlobalString("antlion_5", "whelm and overtake their opponents.")
SetGlobalString("antlion_6", "These bugs pack a mean punch in a mob")
SetGlobalString("antlion_8", "    (Strengths): Very fast and agile, decent")
SetGlobalString("antlion_9", "                         DPS")
SetGlobalString("antlion_10", "(Weaknesses): Rather squishy")
SetGlobalString("antlion_11", "                        ")
SetGlobalString("antlion_12", "   (Strats): Maybe release later so they")
SetGlobalString("antlion_13", "     meet the enemy with your other mobs")
-- Fast Headcrab (x3)
SetGlobalString("triplefastheadcrab_1", "If you ever go to the bathroom at night")
SetGlobalString("triplefastheadcrab_2", "and forget to let your cat in, when you")
SetGlobalString("triplefastheadcrab_3", "turn on the faucet, Fast Headcrabs will")
SetGlobalString("triplefastheadcrab_4", "come pouring out and envelop your body")
SetGlobalString("triplefastheadcrab_5", "and kill you. But if you let your cat in")
SetGlobalString("triplefastheadcrab_6", "you can catch them like we did.")
SetGlobalString("triplefastheadcrab_8", "    (Strengths): 3x multiplier means")
SetGlobalString("triplefastheadcrab_9", "                         you can swarm easier")
SetGlobalString("triplefastheadcrab_10", "(Weaknesses): 1 rocket could probably")
SetGlobalString("triplefastheadcrab_11", "                        wipe half of them out")
SetGlobalString("triplefastheadcrab_12", "   (Strats): Release first to halt the enemy")
SetGlobalString("triplefastheadcrab_13", "                  and rush their ranged units")
-- Manhack (x3)
SetGlobalString("triplemanhack_1", "Remember when I said that HL2 AI's")
SetGlobalString("triplemanhack_2", "freak out when when more than 3")
SetGlobalString("triplemanhack_3", "manhacks attack them? ")
SetGlobalString("triplemanhack_4", "")
SetGlobalString("triplemanhack_5", "                          *Ahem*")
SetGlobalString("triplemanhack_6", "                    You're welcome")
SetGlobalString("triplemanhack_8", "    (Strengths): Numbers, fly like bats")
SetGlobalString("triplemanhack_9", "                         out of hell")
SetGlobalString("triplemanhack_10", "(Weaknesses): ROCKETEERS. 1 Rocket")
SetGlobalString("triplemanhack_11", "                    can probably kill half of them")
SetGlobalString("triplemanhack_12", "   (Strats): Release later so your melee")
SetGlobalString("triplemanhack_13", "                  mobs have already engaged")
-- Rocketeer
SetGlobalString("rocket_1", "The Rocketeer is essentially the Scaredy-")
SetGlobalString("rocket_2", "shroom from Plants Vs Zombies, if instead")
SetGlobalString("rocket_3", "of mucus it shot a PG-7VR AP Tandem-")
SetGlobalString("rocket_4", "Charge shell. While Extremely powerful,")
SetGlobalString("rocket_5", "the Rocketeer is rendered helpless if an")
SetGlobalString("rocket_6", "enemy gets within about 20 feet of him")
SetGlobalString("rocket_8", "    (Strengths): Great Firepower,")
SetGlobalString("rocket_9", "                         Awesome sight to behold")
SetGlobalString("rocket_10", "(Weaknesses): MANHACKS, any fast mob.")
SetGlobalString("rocket_11", "                        Monks out-range him")
SetGlobalString("rocket_12", "   (Strats): Watch the fireworks")
SetGlobalString("rocket_13", "                  Kaboom City Thunder")
-- Barney
SetGlobalString("barney_1", "Barney is a fun loving, trustworthy, AR-")
SetGlobalString("barney_2", "Rifle toting, happy-go-lucky soldier that")
SetGlobalString("barney_3", "has a bit too much health, and packs a")
SetGlobalString("barney_4", "punch from his rifle. Very good at both")
SetGlobalString("barney_5", "ranged encounters and CQB, Barney is a ")
SetGlobalString("barney_6", "mob you can trust")
SetGlobalString("barney_8", "    (Strengths): Great at long range,")
SetGlobalString("barney_9", "                         owes you a beer")
SetGlobalString("barney_10", "(Weaknesses): Monks. (Barney is an")
SetGlobalString("barney_11", "                        atheist)")
SetGlobalString("barney_12", "   (Strats): Release later as his DPS makes")
SetGlobalString("barney_13", "                  him important to keep alive")
-- Zombie (x2)
SetGlobalString("doublezombie_1", "A step up from the regular zombies, these")
SetGlobalString("doublezombie_2", "brothers graduated from USC with a")
SetGlobalString("doublezombie_3", "in Nursing and a minor in Culinary Arts.")
SetGlobalString("doublezombie_4", "As a result, these zombies are the first")
SetGlobalString("doublezombie_5", "to defy the stereotype that zombies eat")
SetGlobalString("doublezombie_6", "brains, by opting for the liver instead")
SetGlobalString("doublezombie_8", "    (Strengths): Taste in Food")
SetGlobalString("doublezombie_9", "                         ")
SetGlobalString("doublezombie_10", "(Weaknesses): Really picky about what")
SetGlobalString("doublezombie_11", "                        they eat")
SetGlobalString("doublezombie_12", "   (Strats): Point them in the general")
SetGlobalString("doublezombie_13", "                  direction of a liver")
-- Vortigaunt
SetGlobalString("vort_1", "Once Slaves on Xen, then Slaves on Earth,")
SetGlobalString("vort_2", "these once friendly aliens have been")
SetGlobalString("vort_3", "turned into electricity sniping, heartless")
SetGlobalString("vort_4", "killing machines that excel at slouching,")
SetGlobalString("vort_5", "taking out flying or ranged units, and ")
SetGlobalString("vort_6", "saying \"Galunga\"")
SetGlobalString("vort_8", "    (Strengths): RANGE and Accuracy")
SetGlobalString("vort_9", "                         Lots of health")
SetGlobalString("vort_10", "(Weaknesses): Lots of weak enemies")
SetGlobalString("vort_11", "                        like Fast Headcrabs")
SetGlobalString("vort_12", "   (Strats): Release early to halt enemies")
SetGlobalString("vort_13", "                  Galalung")
-- Monk
SetGlobalString("monk_1", "Father Grigori drank all the Holy Water")
SetGlobalString("monk_2", "in Ravenholm and ventured out into the ")
SetGlobalString("monk_3", "world. Armed with a Winchester Model")
SetGlobalString("monk_4", "1886 and the immutable word of God,")
SetGlobalString("monk_5", "Gregori brings his devilish aim and")
SetGlobalString("monk_6", "evangilistic spirit wherever he goes.")
SetGlobalString("monk_8", "    (Strengths): Great Range, memorized")
SetGlobalString("monk_9", "                         the book of Revalations")
SetGlobalString("monk_10", "(Weaknesses): Fairly squishy")
SetGlobalString("monk_11", "                        ")
SetGlobalString("monk_12", "   (Strats): Release last and watch him")
SetGlobalString("monk_13", "                  go to work")
-- Suicide
SetGlobalString("suicide_1", "Barry the Blowhard, as he was known in")
SetGlobalString("suicide_2", "college was famous for drinking Pepsi")
SetGlobalString("suicide_3", "with a mouth full of Mentos. He now")
SetGlobalString("suicide_4", "works for the CIA as an under-cover")
SetGlobalString("suicide_5", "operative. He thinks what he's wearing")
SetGlobalString("suicide_6", "is a wire, but its actually Nitrocellulose.")
SetGlobalString("suicide_8", "    (Strengths): Willing to sacrifice for")
SetGlobalString("suicide_9", "                         his country")
SetGlobalString("suicide_10", "(Weaknesses): To his Nitrocellulose,")
SetGlobalString("suicide_11", "                        everyone is hostile")
SetGlobalString("suicide_12", "   (Strats): Get him out of the gates as")
SetGlobalString("suicide_13", "                   quickly as humanly possible")
-- Beefcake
SetGlobalString("beefcake_1", "Beefcakes are the second slowest mob,")
SetGlobalString("beefcake_2", "but have the second highest health in")
SetGlobalString("beefcake_3", "STS. These hunchbacks host and can")
SetGlobalString("beefcake_4", "yeet 3 Black Headcrabs ludicrous")
SetGlobalString("beefcake_5", "distances, negating the largest drawback")
SetGlobalString("beefcake_6", "of the Black Headcrab: its Speed")
SetGlobalString("beefcake_8", "    (Strengths): Health, Spawns 3 Black")
SetGlobalString("beefcake_9", "                         Headcrabs")
SetGlobalString("beefcake_10", "(Weaknesses): Slow moving and a ")
SetGlobalString("beefcake_11", "                        Massive Target")
SetGlobalString("beefcake_12", "   (Strats): Release after other melees,")
SetGlobalString("beefcake_13", "                  to give the crabs a chance")
-- Brute
SetGlobalString("brute_1", "An ex-football player that didn't survive")
SetGlobalString("brute_2", "the 7 Hour War. Even after being taken")
SetGlobalString("brute_3", "over by a headcrab, this once football")
SetGlobalString("brute_4", "player scored higher on the SAT and")
SetGlobalString("brute_5", "almost graduated from community college")
SetGlobalString("brute_6", "when he got expelled for being socialist.") -- i just got the joke
SetGlobalString("brute_8", "    (Strengths): Great health, great DPS,")
SetGlobalString("brute_9", "                 will pull grenade if threatened")
SetGlobalString("brute_10", "(Weaknesses): Self-concious after getting")
SetGlobalString("brute_11", "                        rejected from UCLA")
SetGlobalString("brute_12", "   (Strats): Release first to tank damage")
SetGlobalString("brute_13", "                  and kill enemy melee units")
-- Healer
SetGlobalString("healer_1", "A madman named Petski stole the Medic's")
SetGlobalString("healer_2", "Medi Gun from TF2 and strapped it to a")
SetGlobalString("healer_3", "docile City Scanner with a car battery.")
SetGlobalString("healer_4", "It now follows your team's mobs, passivly")
SetGlobalString("healer_5", "healing any of your team's mobs in its")
SetGlobalString("healer_6", "range. (Dies after 45 sec. for balancing)")
SetGlobalString("healer_8", "    (Strengths): Heals friendly troops,")
SetGlobalString("healer_9", "                         hard to hit, ironic coding")
SetGlobalString("healer_10", "(Weaknesses): MONKS. Dear lord monks")
SetGlobalString("healer_11", "                        shoot these like skeets")
SetGlobalString("healer_12", "   (Strats): Release after the mob you")
SetGlobalString("healer_13", "                  want it to heal")
-- Rocketeer (x2)
SetGlobalString("doublerocket_1", "Whats better than 1 of the best mobs in")
SetGlobalString("doublerocket_2", "this game? Valkyries, but 2x Rocketeers")
SetGlobalString("doublerocket_3", "will have to do! Double the DPS, double")
SetGlobalString("doublerocket_4", "the rockets, double the frustration when")
SetGlobalString("doublerocket_5", "a single fricken headcrab causes these")
SetGlobalString("doublerocket_6", "asshats to blow out their diapers in fear.")
SetGlobalString("doublerocket_8", "    (Strengths): So fricken cool to watch")
SetGlobalString("doublerocket_9", "                         Really high DPS")
SetGlobalString("doublerocket_10", "(Weaknesses): A single mob within 30")
SetGlobalString("doublerocket_11", "               feet makes them wet themselves")
SetGlobalString("doublerocket_12", "   (Strats): Do what you want. They're")
SetGlobalString("doublerocket_13", "                  OP anyways")
-- Zombie (x5)
SetGlobalString("quinzombie_1", "If you want to lag out your game, buddy")
SetGlobalString("quinzombie_2", "this is the right mob for you. With a ")
SetGlobalString("quinzombie_3", "strength 4 Zombie (x5), that single box")
SetGlobalString("quinzombie_4", "will spawn 20 Liver-Loving Zombies at")
SetGlobalString("quinzombie_5", "the start of a round. Now just think: you")
SetGlobalString("quinzombie_6", "have 4 boxes...")
SetGlobalString("quinzombie_8", "    (Strengths): Massive numbers, great")
SetGlobalString("quinzombie_9", "                         DPS, confuses Enemy AI")
SetGlobalString("quinzombie_10", "(Weaknesses): Explosions")
SetGlobalString("quinzombie_11", "                        ")
SetGlobalString("quinzombie_12", "   (Strats): Release first, otherwise they")
SetGlobalString("quinzombie_13", "            will probably clog up your spawn")
-- Antlion Guard
SetGlobalString("antguard_1", "Arguably the strongest mob in STS.")
SetGlobalString("antguard_2", "Highest health, can one hit any other mob")
SetGlobalString("antguard_3", "in the game, and looks cool. However, ")
SetGlobalString("antguard_4", "because it was only ever meant to fight")
SetGlobalString("antguard_5", "the player, it is unable to harm other")
SetGlobalString("antguard_6", "Antlion guards, and dies after 30 seconds")
SetGlobalString("antguard_8", "    (Strengths): Literally Everything")
SetGlobalString("antguard_9", "                         ")
SetGlobalString("antguard_10", "(Weaknesses): Flying mobs, small")
SetGlobalString("antguard_11", "                        numerous mobs")
SetGlobalString("antguard_12", "   (Strats): Release first and watch your")
SetGlobalString("antguard_13", "                  enemies repent")
-- Valkyrie 
SetGlobalString("valkyrie_1", "The holy grail, the crème de la crème, the")
SetGlobalString("valkyrie_2", "hellish fusion of a prison turret and a")
SetGlobalString("valkyrie_3", "city scanner that patrols the streets in")
SetGlobalString("valkyrie_4", "George Orwell's nightmares. This beast")
SetGlobalString("valkyrie_5", "will \"Peacefully restore order\" with blood")
SetGlobalString("valkyrie_6", "running down the street by the gallon")
SetGlobalString("valkyrie_8", "    (Strengths): Hilariously high DPS,")
SetGlobalString("valkyrie_9", "                         Pure-bred killing machine")
SetGlobalString("valkyrie_10", "(Weaknesses): Monks. Like Healers,")
SetGlobalString("valkyrie_11", "                        Monks counter Valkyries")
SetGlobalString("valkyrie_12", "   (Strats): Maybe release later when the")
SetGlobalString("valkyrie_13", "                  enemy is distracted by melees")
-- Antlion (x5)
SetGlobalString("antlion_1", "Lets be honest, you wanted a Valkyrie")
SetGlobalString("antlion_2", "instead of this. You'd even take a ")
SetGlobalString("antlion_3", "Bombing Squad. Hell, even 5x Zombies")
SetGlobalString("antlion_4", "would be better than this crap. But ")
SetGlobalString("antlion_5", "nope, you got unlucky. Sucks for you.")
SetGlobalString("antlion_6", "")
SetGlobalString("antlion_8", "    (Strengths): Cannon Fodder")
SetGlobalString("antlion_9", "                         ")
SetGlobalString("antlion_10", "(Weaknesses): Cannon Fodder")
SetGlobalString("antlion_11", "                        ")
SetGlobalString("antlion_12", "   (Strats): Cannon Fodder")
SetGlobalString("antlion_13", "                  ")
-- Healer (x3)
SetGlobalString("healer_1", "This used to be Medic (x3), but Medics")
SetGlobalString("healer_2", "were laughably weak and I couldn't")
SetGlobalString("healer_3", "figure out how to balance them, so like")
SetGlobalString("healer_4", "any great innovator, I stole the blueprints")
SetGlobalString("healer_5", "of Petski's Healer and mass produced")
SetGlobalString("healer_6", "them, calling them my own design.")
SetGlobalString("healer_8", "    (Strengths): Will distract enemy Monks")
SetGlobalString("healer_9", "                         ")
SetGlobalString("healer_10", "(Weaknesses): Will attract enemy Monks")
SetGlobalString("healer_11", "                        ")
SetGlobalString("healer_12", "   (Strats): Release after the mob you")
SetGlobalString("healer_13", "                  want them to heal")
-- Elite Squad
SetGlobalString("elitesquad_1", "Hired defectors from Dr. Breen's private")
SetGlobalString("elitesquad_2", "garrison, these hardened veterans are")
SetGlobalString("elitesquad_3", "trained to fight all types of enemies, and")
SetGlobalString("elitesquad_4", "work together with other combine units")
SetGlobalString("elitesquad_5", "to form a truly formidable Force. This")
SetGlobalString("elitesquad_6", "squad has 1 Rifleman and 1 Shotgunner.")
SetGlobalString("elitesquad_8", "    (Strengths): Everything: Speed, DPS")
SetGlobalString("elitesquad_9", "                         range, coolness ")
SetGlobalString("elitesquad_10", "(Weaknesses): None ")
SetGlobalString("elitesquad_11", "                        ")
SetGlobalString("elitesquad_12", "   (Strats): The most versitle troop. Use")
SetGlobalString("elitesquad_13", "                  however you see fit")
-- Bombing Squad
SetGlobalString("bombsquad_1", "The newest invention from the Aperture")
SetGlobalString("bombsquad_2", "Science Lab. The boys over there made")
SetGlobalString("bombsquad_3", "the groundbreaking discovery that")
SetGlobalString("bombsquad_4", "strapping explosives to a sentient flying")
SetGlobalString("bombsquad_5", "object is a good idea, and they definitely")
SetGlobalString("bombsquad_6", "came up with that, not the Japanese Navy")
SetGlobalString("bombsquad_8", "    (Strengths): They have been known to")
SetGlobalString("bombsquad_9", "                        play \"Ride of the Valkyries\"")
SetGlobalString("bombsquad_10", "(Weaknesses): None except for Shotgun-")
SetGlobalString("bombsquad_11", "                  ers, because of the knockback")
SetGlobalString("bombsquad_12", "   (Strats): Release first so your mobs")
SetGlobalString("bombsquad_13", "                  aren't in the blast radius")
