-- AINT NO WAYYYYYYYYYYYYYYYYYYYYY
-- Never used lua before but theres GOT to be a better way to do this
-- Headcrab
SetGlobalString("Headcrab_1", "Headcrabs are the default mob, mostly")
SetGlobalString("Headcrab_2", "because they're the worst. Headcrabs")
SetGlobalString("Headcrab_3", "are slow, weak, and inarguably the")
SetGlobalString("Headcrab_4", "least tasty subspecies of crab.")
SetGlobalString("Headcrab_5", "It is recommended you randomize them")
SetGlobalString("Headcrab_6", "as soon as possible")
SetGlobalString("Headcrab_8", "    (Strengths): None")
SetGlobalString("Headcrab_9", "                         ")
SetGlobalString("Headcrab_10", "(Weaknesses): Everything")
SetGlobalString("Headcrab_11", "                        ")
SetGlobalString("Headcrab_12", "   (Strats): Get a new Mob")
SetGlobalString("Headcrab_13", "                   ")
-- Black Headcrab
SetGlobalString("Black Headcrab_1", "Black Headcrabs poision their")
SetGlobalString("Black Headcrab_2", "enemies, bringing most mobs down")
SetGlobalString("Black Headcrab_3", "to 1 health in a single hit. ")
SetGlobalString("Black Headcrab_4", "However, they are painfully slow,")
SetGlobalString("Black Headcrab_5", "and unable to actually finish other")
SetGlobalString("Black Headcrab_6", "mobs off. ")
SetGlobalString("Black Headcrab_8", "    (Strengths): 1 Hit Potential,")
SetGlobalString("Black Headcrab_9", "                        Jumpy Boi")
SetGlobalString("Black Headcrab_10", "(Weaknesses): Its really fricken slow")
SetGlobalString("Black Headcrab_11", "                        ")
SetGlobalString("Black Headcrab_12", "   (Strats): Send it out first and ")
SetGlobalString("Black Headcrab_13", "                  hope it makes it in time")
-- Fast Headcrab
SetGlobalString("Fast Headcrab_1", "Fast headcrabs are the most battle")
SetGlobalString("Fast Headcrab_2", "effective headcrab by far. Super ")
SetGlobalString("Fast Headcrab_3", "strong in great numbers, same health ")
SetGlobalString("Fast Headcrab_4", "as a regular headcrab but 5 times as")
SetGlobalString("Fast Headcrab_5", "fast, these are dangerous opponents ")
SetGlobalString("Fast Headcrab_6", "in high enough numbers")
SetGlobalString("Fast Headcrab_8", "    (Strengths): Speed, Hard to hit")
SetGlobalString("Fast Headcrab_9", "                        ")
SetGlobalString("Fast Headcrab_10", "(Weaknesses): Explosions")
SetGlobalString("Fast Headcrab_11", "                        ")
SetGlobalString("Fast Headcrab_12", "   (Strats): Get as many as you can")
SetGlobalString("Fast Headcrab_13", "                  and unleash the flood")
-- Manhack
SetGlobalString("Manhack_1", "Manhacks are a great nuisance, as ")
SetGlobalString("Manhack_2", "they don't do too much damage but")
SetGlobalString("Manhack_3", "they piss ranged units off, ")
SetGlobalString("Manhack_4", "ESPECIALLY ROCKETEERS! They confuse")
SetGlobalString("Manhack_5", "the crap out of the ai when there")
SetGlobalString("Manhack_6", "are more than 3 attacking one mob.")
SetGlobalString("Manhack_8", "    (Strengths): Speed, Maneuverability,")
SetGlobalString("Manhack_9", "                         hard to hit")
SetGlobalString("Manhack_10", "(Weaknesses): Rather Squishy, Monks")
SetGlobalString("Manhack_11", "                         ")
SetGlobalString("Manhack_12", "   (Strats): Mob melee units,")
SetGlobalString("Manhack_13", "                  confuse ranged units")
-- Crowbar Guy
SetGlobalString("Crowbar Guy_1", "Just a guy that got lost on his way home")
SetGlobalString("Crowbar Guy_2", "from work, so I took him and cloned him.")
SetGlobalString("Crowbar Guy_3", "His AI is pretty dumb sometimes, but for")
SetGlobalString("Crowbar Guy_4", "a common mob, he has average health,")
SetGlobalString("Crowbar Guy_5", "speed, and damage. His Boss says he's")
SetGlobalString("Crowbar Guy_6", "average in every way, and he's right.")
SetGlobalString("Crowbar Guy_8", "    (Strengths): Good Looking")
SetGlobalString("Crowbar Guy_9", "                         ")
SetGlobalString("Crowbar Guy_10", "(Weaknesses): Amidst a Divorce")
SetGlobalString("Crowbar Guy_11", "                         ")
SetGlobalString("Crowbar Guy_12", "   (Strats): Use as cannon fodder")
SetGlobalString("Crowbar Guy_13", "                   ")
-- Fast Torso
SetGlobalString("Fast Torso_1", "Bigg Butt Jim's cousin, ChickenLegg")
SetGlobalString("Fast Torso_2", "Joe. ChickenLegg Joe decided as a child")
SetGlobalString("Fast Torso_3", "to only move around with his arms. Joe")
SetGlobalString("Fast Torso_4", "swung around like a monkey in 'Nam")
SetGlobalString("Fast Torso_5", "before a face full of friendly Napalm")
SetGlobalString("Fast Torso_6", "burned him beyond recognition.")
SetGlobalString("Fast Torso_8", "    (Strengths): Really fast, Tankiness, ")
SetGlobalString("Fast Torso_9", "                         can do 50 pullups")
SetGlobalString("Fast Torso_10", "(Weaknesses): Very few, except flying ")
SetGlobalString("Fast Torso_11", "                        units or Monks")
SetGlobalString("Fast Torso_12", "   (Strats): Release first to make")
SetGlobalString("Fast Torso_13", "                  enemy ranged units miss")
-- Stop Resisting
SetGlobalString("Stop Resisting_1", "An ex-cop with anger issues and a")
SetGlobalString("Stop Resisting_2", "stun stick. Very aggressive, very ")
SetGlobalString("Stop Resisting_3", "effective in numbers, very strong,")
SetGlobalString("Stop Resisting_4", "hates horse raddish, can't drive stick,")
SetGlobalString("Stop Resisting_5", "and after failing to get his counseling")
SetGlobalString("Stop Resisting_6", "degree, beat the professor to death")
SetGlobalString("Stop Resisting_8", "    (Strengths): Health, Speed, Lack of")
SetGlobalString("Stop Resisting_9", "                         Compassion, Batting")
SetGlobalString("Stop Resisting_10", "(Weaknesses): Very few, except")
SetGlobalString("Stop Resisting_11", "                        Rocketeers")
SetGlobalString("Stop Resisting_12", "   (Strats): Release first and watch them")
SetGlobalString("Stop Resisting_13", "                  peacefully disperse a crowd")
-- Zombie Torso
SetGlobalString("Zombie Torso_1", "Back in 'Nam, this guy's name was Bigg")
SetGlobalString("Zombie Torso_2", "Butt Jim. (Yes, Bigg with 2 g's.) However,")
SetGlobalString("Zombie Torso_3", "an IED he found in the jungle made from  ")
SetGlobalString("Zombie Torso_4", "rusty nails and a Sprite can ruined his ")
SetGlobalString("Zombie Torso_5", "chances of ever having a child with ")
SetGlobalString("Zombie Torso_6", "his wife, so she left him back in 71.")
SetGlobalString("Zombie Torso_8", "    (Strengths): Upper Body, lots")
SetGlobalString("Zombie Torso_9", "                        of Health")
SetGlobalString("Zombie Torso_10", "(Weaknesses): PTSD, a fear of the ")
SetGlobalString("Zombie Torso_11", "                        color Green")
SetGlobalString("Zombie Torso_12", "   (Strats): Use as cannon fodder. It ")
SetGlobalString("Zombie Torso_13", "                  reminds him of 'Nam")
-- Medic
SetGlobalString("Medic_1", "After graduating from Harvard Med, this")
SetGlobalString("Medic_2", "kind soul enlisted to serve overseas as")
SetGlobalString("Medic_3", "a combat medic. However, the horrors ")
SetGlobalString("Medic_4", "she saw in the Pacific Theatre scarred")
SetGlobalString("Medic_5", "her, which explains why sometimes her")
SetGlobalString("Medic_6", "AI ignores the mob right next to her")
SetGlobalString("Medic_8", "    (Strengths): Heals ally, can attack")
SetGlobalString("Medic_9", "                         enemies albiet slowly")
SetGlobalString("Medic_10", "(Weaknesses): Ranged units, the horrors")
SetGlobalString("Medic_11", "                        of war made her hollow")
SetGlobalString("Medic_12", "   (Strats): Release them right after the")
SetGlobalString("Medic_13", "                  mob you want her to heal")
-- Shotgun
SetGlobalString("Shotgun_1", "Shotguns are the standard combine")
SetGlobalString("Shotgun_2", "soldier armed with an Italian SPAZ-12.")
SetGlobalString("Shotgun_3", "Very high damage output, moderate")
SetGlobalString("Shotgun_4", "speed, and squadwork capabilities")
SetGlobalString("Shotgun_5", "heavily outweigh its occasional")
SetGlobalString("Shotgun_6", "numskulled AI")
SetGlobalString("Shotgun_8", "    (Strengths): High DPS, can nail a clay")
SetGlobalString("Shotgun_9", "                         pigeon at 100 yards")
SetGlobalString("Shotgun_10", "(Weaknesses): Will occasionally default")
SetGlobalString("Shotgun_11", "                        to melee charges")
SetGlobalString("Shotgun_12", "   (Strats): Release after other melee units")
SetGlobalString("Shotgun_13", "                  to make full use of his gun")
-- SMG
SetGlobalString("SMG_1", "SMGS are the standard Combine Soldier")
SetGlobalString("SMG_2", "armed with a German MP7. The perfect")
SetGlobalString("SMG_3", "balance of range, damage, health, speed,")
SetGlobalString("SMG_4", "and reliability. Works really well with")
SetGlobalString("SMG_5", "other Combine Units, and provides great")
SetGlobalString("SMG_6", "backup for faster Melee units.")
SetGlobalString("SMG_8", "    (Strengths): Good DPS, Good Health")
SetGlobalString("SMG_9", "                         Good Aim, Reliable")
SetGlobalString("SMG_10", "(Weaknesses): None in particular")
SetGlobalString("SMG_11", "                        ")
SetGlobalString("SMG_12", "   (Strats): The Ideal soldier. Use for ")
SetGlobalString("SMG_13", "                  whatever purpose you wish")
-- Metrocop
SetGlobalString("Metrocop_1", "These Metro Police are a good step up")
SetGlobalString("Metrocop_2", "from Common mobs, as they are armed")
SetGlobalString("Metrocop_3", "with a 9mm Pistol, and a Manhack that")
SetGlobalString("Metrocop_4", "they can deploy. Overall smart AI, added")
SetGlobalString("Metrocop_5", "bonus of a manhack, and decent accuracy")
SetGlobalString("Metrocop_6", "make this a decent mob.")
SetGlobalString("Metrocop_8", "    (Strengths): Range, Manhack")
SetGlobalString("Metrocop_9", "                         ")
SetGlobalString("Metrocop_10", "(Weaknesses): Zombies or other fast ")
SetGlobalString("Metrocop_11", "                        melee mobs")
SetGlobalString("Metrocop_12", "   (Strats): Release after some melees to")
SetGlobalString("Metrocop_13", "                  keep it out of direct danger")
-- Stop Resisting (x2)
SetGlobalString("Stop Resisting (x2)_1", "After breaking into a school and beating")
SetGlobalString("Stop Resisting (x2)_2", "eight 1st graders to death in \"self ")
SetGlobalString("Stop Resisting (x2)_3", "defense,\" the Minneapolis Police Depart.")
SetGlobalString("Stop Resisting (x2)_4", "transfered these officers to Black Mesa,")
SetGlobalString("Stop Resisting (x2)_5", "where their overagresive habbits and their")
SetGlobalString("Stop Resisting (x2)_6", "baseball abilities could be better studied")
SetGlobalString("Stop Resisting (x2)_8", "    (Strengths): Health, Speed, Lack of")
SetGlobalString("Stop Resisting (x2)_9", "                         Compassion, Batting")
SetGlobalString("Stop Resisting (x2)_10", "(Weaknesses): Very few, except")
SetGlobalString("Stop Resisting (x2)_11", "                        Rocketeers")
SetGlobalString("Stop Resisting (x2)_12", "   (Strats): Release first and watch them")
SetGlobalString("Stop Resisting (x2)_13", "                  peacefully disperse a crowd")
-- Zombie
SetGlobalString("Zombie_1", "Zombies are actually the Fast Zombie")
SetGlobalString("Zombie_2", "HL2 because Regular Zombies were way")
SetGlobalString("Zombie_3", "too slow. Zombies are fast, fairly")
SetGlobalString("Zombie_4", "light mobs that deal good melee damage,")
SetGlobalString("Zombie_5", "have a pretty good amount of health, and,")
SetGlobalString("Zombie_6", "like Antlioins, are great in groups")
SetGlobalString("Zombie_8", "    (Strengths): Fast, deal good damage,")
SetGlobalString("Zombie_9", "                         Got massive hops")
SetGlobalString("Zombie_10", "(Weaknesses): Explosions, Monks,")
SetGlobalString("Zombie_11", "                        has a 680 SAT Score")
SetGlobalString("Zombie_12", "   (Strats): Due to their speed, release")
SetGlobalString("Zombie_13", "                  them after other melee units")
-- Antlion
SetGlobalString("Antlion_1", "Fast, agile, jumpy, Antlions are a solid")
SetGlobalString("Antlion_2", "offensive mob. Many of them served")
SetGlobalString("Antlion_3", "storming Nova Prospekt, making use of")
SetGlobalString("Antlion_4", "their wings and their numbers to over-")
SetGlobalString("Antlion_5", "whelm and overtake their opponents.")
SetGlobalString("Antlion_6", "These bugs pack a mean punch in a mob")
SetGlobalString("Antlion_8", "    (Strengths): Very fast and agile, decent")
SetGlobalString("Antlion_9", "                         DPS")
SetGlobalString("Antlion_10", "(Weaknesses): Rather squishy")
SetGlobalString("Antlion_11", "                        ")
SetGlobalString("Antlion_12", "   (Strats): Maybe release later so they")
SetGlobalString("Antlion_13", "     meet the enemy with your other mobs")
-- Fast Headcrab (x3)
SetGlobalString("Fast Headcrab (x3)_1", "If you ever go to the bathroom at night")
SetGlobalString("Fast Headcrab (x3)_2", "and forget to let your cat in, when you")
SetGlobalString("Fast Headcrab (x3)_3", "turn on the faucet, Fast Headcrabs will")
SetGlobalString("Fast Headcrab (x3)_4", "come pouring out and envelop your body")
SetGlobalString("Fast Headcrab (x3)_5", "and kill you. But if you let your cat in")
SetGlobalString("Fast Headcrab (x3)_6", "you can catch them like we did.")
SetGlobalString("Fast Headcrab (x3)_8", "    (Strengths): 3x multiplier means")
SetGlobalString("Fast Headcrab (x3)_9", "                         you can swarm easier")
SetGlobalString("Fast Headcrab (x3)_10", "(Weaknesses): 1 rocket could probably")
SetGlobalString("Fast Headcrab (x3)_11", "                        wipe half of them out")
SetGlobalString("Fast Headcrab (x3)_12", "   (Strats): Release first to halt the enemy")
SetGlobalString("Fast Headcrab (x3)_13", "                  and rush their ranged units")
-- Manhack (x3)
SetGlobalString("Manhack (x3)_1", "Remember when I said that HL2 AI's")
SetGlobalString("Manhack (x3)_2", "freak out when when more than 3")
SetGlobalString("Manhack (x3)_3", "manhacks attack them? ")
SetGlobalString("Manhack (x3)_4", "")
SetGlobalString("Manhack (x3)_5", "                          *Ahem*")
SetGlobalString("Manhack (x3)_6", "                    You're welcome")
SetGlobalString("Manhack (x3)_8", "    (Strengths): Numbers, fly like bats")
SetGlobalString("Manhack (x3)_9", "                         out of hell")
SetGlobalString("Manhack (x3)_10", "(Weaknesses): ROCKETEERS. 1 Rocket")
SetGlobalString("Manhack (x3)_11", "                    can probably kill half of them")
SetGlobalString("Manhack (x3)_12", "   (Strats): Release later so your melee")
SetGlobalString("Manhack (x3)_13", "                  mobs have already engaged")
-- Rocketeer
SetGlobalString("Rocketeer_1", "The Rocketeer is essentially the Scaredy-")
SetGlobalString("Rocketeer_2", "shroom from Plants Vs Zombies, if instead")
SetGlobalString("Rocketeer_3", "of mucus it shot a PG-7VR AP Tandem-")
SetGlobalString("Rocketeer_4", "Charge shell. While Extremely powerful,")
SetGlobalString("Rocketeer_5", "the Rocketeer is rendered helpless if an")
SetGlobalString("Rocketeer_6", "enemy gets within about 20 feet of him")
SetGlobalString("Rocketeer_8", "    (Strengths): Great Firepower,")
SetGlobalString("Rocketeer_9", "                         Awesome sight to behold")
SetGlobalString("Rocketeer_10", "(Weaknesses): MANHACKS, any fast mob.")
SetGlobalString("Rocketeer_11", "                        Monks out-range him")
SetGlobalString("Rocketeer_12", "   (Strats): Watch the fireworks")
SetGlobalString("Rocketeer_13", "                  Kaboom City Thunder")
-- Barney
SetGlobalString("Barney_1", "Barney is a fun loving, trustworthy, AR-")
SetGlobalString("Barney_2", "Rifle toting, happy-go-lucky soldier that")
SetGlobalString("Barney_3", "has a bit too much health, and packs a")
SetGlobalString("Barney_4", "punch from his rifle. Very good at both")
SetGlobalString("Barney_5", "ranged encounters and CQB, Barney is a ")
SetGlobalString("Barney_6", "mob you can trust")
SetGlobalString("Barney_8", "    (Strengths): Great at long range,")
SetGlobalString("Barney_9", "                         owes you a beer")
SetGlobalString("Barney_10", "(Weaknesses): Monks. (Barney is an")
SetGlobalString("Barney_11", "                        atheist)")
SetGlobalString("Barney_12", "   (Strats): Release later as his DPS makes")
SetGlobalString("Barney_13", "                  him important to keep alive")
-- Zombie (x2)
SetGlobalString("Zombie (x2)_1", "A step up from the regular zombies, these")
SetGlobalString("Zombie (x2)_2", "brothers graduated from USC with a")
SetGlobalString("Zombie (x2)_3", "in Nursing and a minor in Culinary Arts.")
SetGlobalString("Zombie (x2)_4", "As a result, these zombies are the first")
SetGlobalString("Zombie (x2)_5", "to defy the stereotype that zombies eat")
SetGlobalString("Zombie (x2)_6", "brains, by opting for the liver instead")
SetGlobalString("Zombie (x2)_8", "    (Strengths): Taste in Food")
SetGlobalString("Zombie (x2)_9", "                         ")
SetGlobalString("Zombie (x2)_10", "(Weaknesses): Really picky about what")
SetGlobalString("Zombie (x2)_11", "                        they eat")
SetGlobalString("Zombie (x2)_12", "   (Strats): Point them in the general")
SetGlobalString("Zombie (x2)_13", "                  direction of a liver")
-- Vortigaunt
SetGlobalString("Vortigaunt_1", "Once Slaves on Xen, then Slaves on Earth,")
SetGlobalString("Vortigaunt_2", "these once friendly aliens have been")
SetGlobalString("Vortigaunt_3", "turned into electricity sniping, heartless")
SetGlobalString("Vortigaunt_4", "killing machines that excel at slouching,")
SetGlobalString("Vortigaunt_5", "taking out flying or ranged units, and ")
SetGlobalString("Vortigaunt_6", "saying \"Galunga\"")
SetGlobalString("Vortigaunt_8", "    (Strengths): RANGE and Accuracy")
SetGlobalString("Vortigaunt_9", "                         Lots of health")
SetGlobalString("Vortigaunt_10", "(Weaknesses): Lots of weak enemies")
SetGlobalString("Vortigaunt_11", "                        like Fast Headcrabs")
SetGlobalString("Vortigaunt_12", "   (Strats): Release early to halt enemies")
SetGlobalString("Vortigaunt_13", "                  Galalung")
-- Monk
SetGlobalString("Monk_1", "Father Grigori drank all the Holy Water")
SetGlobalString("Monk_2", "in Ravenholm and ventured out into the ")
SetGlobalString("Monk_3", "world. Armed with a Winchester Model")
SetGlobalString("Monk_4", "1886 and the immutable word of God,")
SetGlobalString("Monk_5", "Gregori brings his devilish aim and")
SetGlobalString("Monk_6", "evangilistic spirit wherever he goes.")
SetGlobalString("Monk_8", "    (Strengths): Great Range, memorized")
SetGlobalString("Monk_9", "                         the book of Revalations")
SetGlobalString("Monk_10", "(Weaknesses): Fairly squishy")
SetGlobalString("Monk_11", "                        ")
SetGlobalString("Monk_12", "   (Strats): Release last and watch him")
SetGlobalString("Monk_13", "                  go to work")
-- Suicide
SetGlobalString("Suicide_1", "Barry the Blowhard, as he was known in")
SetGlobalString("Suicide_2", "college was famous for drinking Pepsi")
SetGlobalString("Suicide_3", "with a mouth full of Mentos. He now")
SetGlobalString("Suicide_4", "works for the CIA as an under-cover")
SetGlobalString("Suicide_5", "operative. He thinks what he's wearing")
SetGlobalString("Suicide_6", "is a wire, but its actually Nitrocellulose.")
SetGlobalString("Suicide_8", "    (Strengths): Willing to sacrifice for")
SetGlobalString("Suicide_9", "                         his country")
SetGlobalString("Suicide_10", "(Weaknesses): To his Nitrocellulose,")
SetGlobalString("Suicide_11", "                        everyone is hostile")
SetGlobalString("Suicide_12", "   (Strats): Get him out of the gates as")
SetGlobalString("Suicide_13", "                   quickly as humanly possible")
-- Beefcake
SetGlobalString("Beefcake_1", "Beefcakes are the second slowest mob,")
SetGlobalString("Beefcake_2", "but have the second highest health in")
SetGlobalString("Beefcake_3", "STS. These hunchbacks host and can")
SetGlobalString("Beefcake_4", "yeet 3 Black Headcrabs ludicrous")
SetGlobalString("Beefcake_5", "distances, negating the largest drawback")
SetGlobalString("Beefcake_6", "of the Black Headcrab: its Speed")
SetGlobalString("Beefcake_8", "    (Strengths): Health, Spawns 3 Black")
SetGlobalString("Beefcake_9", "                         Headcrabs")
SetGlobalString("Beefcake_10", "(Weaknesses): Slow moving and a ")
SetGlobalString("Beefcake_11", "                        Massive Target")
SetGlobalString("Beefcake_12", "   (Strats): Release after other melees,")
SetGlobalString("Beefcake_13", "                  to give the crabs a chance")
-- Brute
SetGlobalString("Brute_1", "An ex-football player that didn't survive")
SetGlobalString("Brute_2", "the 7 Hour War. Even after being taken")
SetGlobalString("Brute_3", "over by a headcrab, this once football")
SetGlobalString("Brute_4", "player scored higher on the SAT and")
SetGlobalString("Brute_5", "almost graduated from community college")
SetGlobalString("Brute_6", "when he got expelled for being socialist.") -- lol what??? | this joke doesn't make sense unless its like three layers deep in irony
SetGlobalString("Brute_8", "    (Strengths): Great health, great DPS,")
SetGlobalString("Brute_9", "                 will pull grenade if threatened")
SetGlobalString("Brute_10", "(Weaknesses): Self-concious after getting")
SetGlobalString("Brute_11", "                        rejected from UCLA")
SetGlobalString("Brute_12", "   (Strats): Release first to tank damage")
SetGlobalString("Brute_13", "                  and kill enemy melee units")
-- Healer
SetGlobalString("Healer_1", "A madman named Petski stole the Medic's")
SetGlobalString("Healer_2", "Medi Gun from TF2 and strapped it to a")
SetGlobalString("Healer_3", "docile City Scanner with a car battery.")
SetGlobalString("Healer_4", "It now follows your team's mobs, passivly")
SetGlobalString("Healer_5", "healing any of your team's mobs in its")
SetGlobalString("Healer_6", "range. (Dies after 45 sec. for balancing)")
SetGlobalString("Healer_8", "    (Strengths): Heals friendly troops,")
SetGlobalString("Healer_9", "                         hard to hit, ironic coding")
SetGlobalString("Healer_10", "(Weaknesses): MONKS. Dear lord monks")
SetGlobalString("Healer_11", "                        shoot these like skeets")
SetGlobalString("Healer_12", "   (Strats): Release after the mob you")
SetGlobalString("Healer_13", "                  want it to heal")
-- Rocketeer (x2)
SetGlobalString("Rocketeer (x2)_1", "Whats better than 1 of the best mobs in")
SetGlobalString("Rocketeer (x2)_2", "this game? Valkyries, but 2x Rocketeers")
SetGlobalString("Rocketeer (x2)_3", "will have to do! Double the DPS, double")
SetGlobalString("Rocketeer (x2)_4", "the rockets, double the frustration when")
SetGlobalString("Rocketeer (x2)_5", "a single fricken headcrab causes these")
SetGlobalString("Rocketeer (x2)_6", "asshats to blow out their diapers in fear.")
SetGlobalString("Rocketeer (x2)_8", "    (Strengths): So fricken cool to watch")
SetGlobalString("Rocketeer (x2)_9", "                         Really high DPS")
SetGlobalString("Rocketeer (x2)_10", "(Weaknesses): A single mob within 30")
SetGlobalString("Rocketeer (x2)_11", "               feet makes them wet themselves")
SetGlobalString("Rocketeer (x2)_12", "   (Strats): Do what you want. They're")
SetGlobalString("Rocketeer (x2)_13", "                  OP anyways")
-- Zombie (x5)
SetGlobalString("Zombie (x5)_1", "If you want to lag out your game, buddy")
SetGlobalString("Zombie (x5)_2", "this is the right mob for you. With a ")
SetGlobalString("Zombie (x5)_3", "strength 4 Zombie (x5), that single box")
SetGlobalString("Zombie (x5)_4", "will spawn 20 Liver-Loving Zombies at")
SetGlobalString("Zombie (x5)_5", "the start of a round. Now just think: you")
SetGlobalString("Zombie (x5)_6", "have 4 boxes...")
SetGlobalString("Zombie (x5)_8", "    (Strengths): Massive numbers, great")
SetGlobalString("Zombie (x5)_9", "                         DPS, confuses Enemy AI")
SetGlobalString("Zombie (x5)_10", "(Weaknesses): Explosions")
SetGlobalString("Zombie (x5)_11", "                        ")
SetGlobalString("Zombie (x5)_12", "   (Strats): Release first, otherwise they")
SetGlobalString("Zombie (x5)_13", "            will probably clog up your spawn")
-- Antlion Guard
SetGlobalString("Antlion Guard_1", "Arguably the strongest mob in STS.")
SetGlobalString("Antlion Guard_2", "Highest health, can one hit any other mob")
SetGlobalString("Antlion Guard_3", "in the game, and looks cool. However, ")
SetGlobalString("Antlion Guard_4", "because it was only ever meant to fight")
SetGlobalString("Antlion Guard_5", "the player, it is unable to harm other")
SetGlobalString("Antlion Guard_6", "Antlion guards, and dies after 30 seconds")
SetGlobalString("Antlion Guard_8", "    (Strengths): Literally Everything")
SetGlobalString("Antlion Guard_9", "                         ")
SetGlobalString("Antlion Guard_10", "(Weaknesses): Flying mobs, small")
SetGlobalString("Antlion Guard_11", "                        numerous mobs")
SetGlobalString("Antlion Guard_12", "   (Strats): Release first and watch your")
SetGlobalString("Antlion Guard_13", "                  enemies repent")
-- Valkyrie 
SetGlobalString("Valkyrie_1", "The holy grail, the crème de la crème, the")
SetGlobalString("Valkyrie_2", "hellish fusion of a prison turret and a")
SetGlobalString("Valkyrie_3", "city scanner that patrols the streets in")
SetGlobalString("Valkyrie_4", "George Orwell's nightmares. This beast")
SetGlobalString("Valkyrie_5", "will \"Peacefully restore order\" with blood")
SetGlobalString("Valkyrie_6", "running down the street by the gallon")
SetGlobalString("Valkyrie_8", "    (Strengths): Hilariously high DPS,")
SetGlobalString("Valkyrie_9", "                         Pure-bred killing machine")
SetGlobalString("Valkyrie_10", "(Weaknesses): Monks. Like Healers,")
SetGlobalString("Valkyrie_11", "                        Monks counter Valkyries")
SetGlobalString("Valkyrie_12", "   (Strats): Maybe release later when the")
SetGlobalString("Valkyrie_13", "                  enemy is distracted by melees")
-- Antlion (x5)
SetGlobalString("Antlion (x5)_1", "Lets be honest, you wanted a Valkyrie")
SetGlobalString("Antlion (x5)_2", "instead of this. You'd even take a ")
SetGlobalString("Antlion (x5)_3", "Bombing Squad. Hell, even 5x Zombies")
SetGlobalString("Antlion (x5)_4", "would be better than this crap. But ")
SetGlobalString("Antlion (x5)_5", "nope, you got unlucky. Sucks for you.")
SetGlobalString("Antlion (x5)_6", "")
SetGlobalString("Antlion (x5)_8", "    (Strengths): Cannon Fodder")
SetGlobalString("Antlion (x5)_9", "                         ")
SetGlobalString("Antlion (x5)_10", "(Weaknesses): Cannon Fodder")
SetGlobalString("Antlion (x5)_11", "                        ")
SetGlobalString("Antlion (x5)_12", "   (Strats): Cannon Fodder")
SetGlobalString("Antlion (x5)_13", "                  ")
-- Healer (x3)
SetGlobalString("Healer (x3)_1", "This used to be Medic (x3), but Medics")
SetGlobalString("Healer (x3)_2", "were laughably weak and I couldn't")
SetGlobalString("Healer (x3)_3", "figure out how to balance them, so like")
SetGlobalString("Healer (x3)_4", "any great innovator, I stole the blueprints")
SetGlobalString("Healer (x3)_5", "of Petski's Healer and mass produced")
SetGlobalString("Healer (x3)_6", "them, calling them my own design.")
SetGlobalString("Healer (x3)_8", "    (Strengths): Will distract enemy Monks")
SetGlobalString("Healer (x3)_9", "                         ")
SetGlobalString("Healer (x3)_10", "(Weaknesses): Will attract enemy Monks")
SetGlobalString("Healer (x3)_11", "                        ")
SetGlobalString("Healer (x3)_12", "   (Strats): Release after the mob you")
SetGlobalString("Healer (x3)_13", "                  want them to heal")
-- Elite Squad
SetGlobalString("Elite Squad_1", "Hired defectors from Dr. Breen's private")
SetGlobalString("Elite Squad_2", "garrison, these hardened veterans are")
SetGlobalString("Elite Squad_3", "trained to fight all types of enemies, and")
SetGlobalString("Elite Squad_4", "work together with other combine units")
SetGlobalString("Elite Squad_5", "to form a truly formidable Force. This")
SetGlobalString("Elite Squad_6", "squad has 1 Rifleman and 1 Shotgunner.")
SetGlobalString("Elite Squad_8", "    (Strengths): Everything: Speed, DPS")
SetGlobalString("Elite Squad_9", "                         range, coolness ")
SetGlobalString("Elite Squad_10", "(Weaknesses): None ")
SetGlobalString("Elite Squad_11", "                        ")
SetGlobalString("Elite Squad_12", "   (Strats): The most versitle troop. Use")
SetGlobalString("Elite Squad_13", "                  however you see fit")
-- Bombing Squad
SetGlobalString("Bombing Squad_1", "The newest invention from the Aperture")
SetGlobalString("Bombing Squad_2", "Science Lab. The boys over there made")
SetGlobalString("Bombing Squad_3", "the groundbreaking discovery that")
SetGlobalString("Bombing Squad_4", "strapping explosives to a sentient flying")
SetGlobalString("Bombing Squad_5", "object is a good idea, and they definitely")
SetGlobalString("Bombing Squad_6", "came up with that, not the Japanese Navy")
SetGlobalString("Bombing Squad_8", "    (Strengths): They have been known to")
SetGlobalString("Bombing Squad_9", "                        play \"Ride of the Valkyries\"")
SetGlobalString("Bombing Squad_10", "(Weaknesses): None except for Shotgun-")
SetGlobalString("Bombing Squad_11", "                  ers, because of the knockback")
SetGlobalString("Bombing Squad_12", "   (Strats): Release first so your mobs")
SetGlobalString("Bombing Squad_13", "                  aren't in the blast radius")